####### cob_offset #######
cob_x_offset_m : -0.030
cob_y_offset_m :  0.000

####### FeedForward #####
hip_roll_swap_angle_rad : 0

########## Gain ########
# by gyro
foot_roll_gyro_p_gain : 0.3 #5 #0.3
foot_roll_gyro_d_gain : 0.0 #0.0

foot_pitch_gyro_p_gain : 0.3 #5 #0.5
foot_pitch_gyro_d_gain : 0.0 #0.0

# by imu
foot_roll_angle_p_gain : 0.75 #0.4
foot_roll_angle_d_gain : 0.0 #0.0

foot_pitch_angle_p_gain : 0.75 #0.55
foot_pitch_angle_d_gain : 0.0 #0.0

# by ft sensor
foot_x_force_p_gain : 0.065 #0.035
foot_x_force_d_gain : 0.0 #0.0

foot_y_force_p_gain : 0.065 #0.035
foot_y_force_d_gain : 0.00 #0.00

foot_z_force_p_gain : 0.008 #0.015 #0.001
foot_z_force_d_gain : 0.0 #0.000

#### warnning
foot_roll_torque_p_gain : 0.0012 #0.0012
foot_roll_torque_d_gain : 0.0 #0.00

foot_pitch_torque_p_gain : 0.001 #0.001
foot_pitch_torque_d_gain : 0.0 #0.0

########## CUT OFF FREQUENCY ##########
# by gyro
roll_gyro_cut_off_frequency  : 40.0
pitch_gyro_cut_off_frequency : 40.0

# by imu
roll_angle_cut_off_frequency  : 40.0
pitch_angle_cut_off_frequency : 40.0

# by ft sensor

foot_x_force_cut_off_frequency : 20.0 #20.0
foot_y_force_cut_off_frequency : 20.0 #20.0
foot_z_force_cut_off_frequency : 20.0 #20.0
foot_roll_torque_cut_off_frequency : 20.0 #20.0
foot_pitch_torque_cut_off_frequency : 20.0 #20.0
